# Generated by Django 2.1.3 on 2018-11-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20181103_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='messaging.User'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='messaging.User'),
        ),
        migrations.AddField(
            model_name='grouphistory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.DirectMessage'),
        ),
        migrations.AddField(
            model_name='grouphistory',
            name='last_seen_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Message'),
        ),
        migrations.AddField(
            model_name='grouphistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.User'),
        ),
        migrations.AddField(
            model_name='directmessagehistory',
            name='direct_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.DirectMessage'),
        ),
        migrations.AddField(
            model_name='directmessagehistory',
            name='last_seen_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Message'),
        ),
        migrations.AddField(
            model_name='directmessagehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.User'),
        ),
    ]
