# Generated by Django 2.1.3 on 2018-11-11 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20181111_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouphistory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Group'),
        ),
    ]
