# Generated by Django 2.1.3 on 2018-11-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20181114_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_id',
            field=models.IntegerField(null=True),
        ),
    ]
